CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       libelle VARCHAR(50) NOT NULL,
                       CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       username VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       id_roles BIGINT NOT NULL,
                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT fk_users_roles FOREIGN KEY (id_roles) REFERENCES roles(id)
);

CREATE TABLE studies (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         name VARCHAR(255) NOT NULL,
                         description VARCHAR(255),
                         user_id BIGINT NOT NULL,
                         CONSTRAINT pk_studies PRIMARY KEY (id),
                         CONSTRAINT fk_studies_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE sites (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       start_date DATE,
                       end_date DATE,
                       study_id BIGINT NOT NULL,
                       CONSTRAINT pk_sites PRIMARY KEY (id),
                       CONSTRAINT fk_sites_study FOREIGN KEY (study_id) REFERENCES studies(id) ON DELETE CASCADE
);

CREATE TABLE patients (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          subject_number INT NOT NULL,
                          site_id BIGINT NOT NULL,
                          CONSTRAINT pk_patients PRIMARY KEY (id),
                          CONSTRAINT fk_patients_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);

CREATE TABLE visits (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        name VARCHAR(255) NOT NULL,
                        visit_date DATE NOT NULL,
                        patient_id BIGINT NOT NULL,
                        study_id BIGINT NOT NULL,
                        CONSTRAINT pk_visits PRIMARY KEY (id),
                        CONSTRAINT fk_visits_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
                        CONSTRAINT fk_visits_study FOREIGN KEY (study_id) REFERENCES studies(id) ON DELETE CASCADE
);

CREATE TABLE vital_signs (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             type VARCHAR(50) NOT NULL,
                             value DOUBLE PRECISION NOT NULL,
                             unit VARCHAR(20),
                             measured_at TIMESTAMP NOT NULL,
                             visit_id BIGINT NOT NULL,
                             CONSTRAINT pk_vital_signs PRIMARY KEY (id),
                             CONSTRAINT fk_vitalsigns_visit FOREIGN KEY (visit_id) REFERENCES visits(id) ON DELETE CASCADE
);
