CREATE TABLE patients
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subject_number      INT NULL,
    visit_id            BIGINT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

CREATE TABLE studies
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255) NULL,
    description     VARCHAR(255) NULL,
    patient_id      BIGINT NULL,
    CONSTRAINT pk_studies PRIMARY KEY (id)
);

CREATE TABLE visits
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) NULL,
    date          date         NULL,
    vital_sign_id BIGINT       NULL,
    CONSTRAINT pk_visits PRIMARY KEY (id)
);

CREATE TABLE vital_signs
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255) NULL,
    description         VARCHAR(255) NULL,
    temperature         INT NULL,
    pulse               INT NULL,
    systolic_pressure   INT NULL,
    diastolic_pressure  INT NULL,
    weight              INT NULL,
    height              INT NULL,
    CONSTRAINT pk_vitalsigns PRIMARY KEY (id)
);

ALTER TABLE visits
    ADD CONSTRAINT FK_VISITS_ON_VITALSIGN FOREIGN KEY (vital_sign_id) REFERENCES vital_signs (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);

ALTER TABLE patients
    ADD CONSTRAINT FK_PATIENTS_ON_VISIT FOREIGN KEY (visit_id) REFERENCES visits (id);
