export enum VitalSignType {
  TEMPERATURE = 'TEMPERATURE',
  HEART_RATE = 'HEART_RATE',
  SYSTOLIC_PRESSURE = 'SYSTOLIC_PRESSURE',
  DIASTOLIC_PRESSURE = 'DIASTOLIC_PRESSURE',
  WEIGHT = 'WEIGHT',
  HEIGHT = 'HEIGHT'
}